### ISSUE TITLE
small model mismatch owapi v3

### ISSUE THREAD

**Issue by snakelayer** [verath/owbot-bot#3]
Just FYI, the `win_rate` field in the `competitive` struct returned in the owapi v3 response is a float. I don't know if this was a change or always like this, but it currently causes logger warnings:

`WARN[0003] Ignoring type error when decoding response as JSON  error=json: cannot unmarshal number 43.18 into Go struct field .win_Rate of type int method=GET module=overwatch...`

This change in overwatch.go fixes it, if you were still inclined:

```
OverallStats struct {
	CompRank int     `json:"comprank"`
	Games    int     `json:"games"`
	Level    int     `json:"level"`
	Losses   int     `json:"losses"`
	Prestige int     `json:"prestige"`
	Wins     int     `json:"wins"`
	WinRate  float32 `json:"win_Rate"`
}
```

**Comment by verath** [comment]
Hey, thanks! 

Not actively using the bot, but looks like a small enough change to be worth fixing :).

Your fork looks cool btw! I'm glad you decided to use discordgo instead of my discord stuff. Writing that part was great for learning, but actually using it instead of discordgo doesn't really make sense.

Peter

**Comment by snakelayer** [comment]
Thanks!

I started the fork partly to learn Go as well, and your project was the perfect starting point! Replacing the discord component with discordgo was very straightforward. Thanks for keeping that boundary clean. :D
